import "./globals.css";
export const metadata = {
  title: "App Router",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>This is header</h1>
        </header>
        {children}
        <footer>
          <h1>This is footer</h1>
        </footer>
      </body>
    </html>
  );
}
